export const FETCH_LIST_CARDS_BEGIN = 'FETCH_LIST_CARDS_BEGIN';
export const FETCH_LIST_CARDS_SUCCESS = 'FETCH_LIST_CARDS_SUCCESS';
export const FETCH_LIST_CARDS_FAILURE = 'FETCH_LIST_CARDS_FAILURE';

export const GET_CARD_BEGIN = 'GET_CARD_BEGIN';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAILURE = 'GET_CARD_FAILURE';